name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Build Release
        run: |
          chmod +x ./build.sh
          ./build.sh release -t:false

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/Release/**
